### ISSUE TITLE
NoClassDefFound Error from SBT Java Applications

### ISSUE THREAD

**Issue by sbasegmez** [OpenNTF/SocialSDK#1543]
The following piece of code for a standalone Java application normally works. In case we provide a wrong password, it will throw an uncatchable NoClassDefFoundError with the stack trace below...

ClientService.processResponse gets an error code (404) from the remote server. In this case, it doesn't fail, instead, tries to redirect user to the login page. However, since it's a standalone application, there is no servlet context. It fails with an uncatchable error and developer has no chance to recover the application in case of a wrong password.

I'm using this for a background application where username/password is pre-configured and such a failure will result in an unstable environment.

In case of a standalone application, redirection would be canceled or better, a way to test authentication within the endpoint would be fantastic! 

Thanks.

```java
RuntimeFactory runtimeFactory=null;
Application application=null;
Context context = null;

try {
	runtimeFactory=new RuntimeFactoryStandalone();
	application=runtimeFactory.initApplication(null);
	context = Context.init(application, null, null);
			
	ConnectionsBasicEndpoint endpoint= new ConnectionsBasicEndpoint();

	endpoint.setUrl("https://connectionserver.com");
	endpoint.setForceTrustSSLCertificate(true);
	endpoint.login("someuser", "somepassword"); // password is wrong
	
	System.out.println(endpoint.isAuthenticated());
	
	ProfileService ps=new ProfileService(endpoint);

	Profile me=ps.getMyProfile();
	
	System.out.println(me.getName());
} catch(Throwable t) {
	t.printStackTrace();
} finally {
	if (context != null)
		Context.destroy(context);
	if (application != null)
		Application.destroy(application);
}
```

Trace:

java.lang.NoClassDefFoundError: javax.servlet.http.HttpServletRequest
	at com.ibm.commons.runtime.Context.getHttpRequest(Context.java:115)
	at com.ibm.sbt.services.endpoints.BasicEndpoint.authenticate(BasicEndpoint.java:151)
	at com.ibm.sbt.services.client.ClientService.forceAuthentication(ClientService.java:296)
	at com.ibm.sbt.services.client.ClientService.processResponse(ClientService.java:1154)
	at com.ibm.sbt.services.client.ClientService._xhr(ClientService.java:1072)
	at com.ibm.sbt.services.client.ClientService.execRequest(ClientService.java:1037)
	at com.ibm.sbt.services.client.ClientService.xhr(ClientService.java:997)
	at com.ibm.sbt.services.client.ClientService.get(ClientService.java:873)
	at com.ibm.sbt.services.client.ClientService.get(ClientService.java:869)
	at com.ibm.sbt.services.client.ClientService.get(ClientService.java:859)
	at com.ibm.sbt.services.client.ClientService.get(ClientService.java:846)
	at com.ibm.sbt.services.client.connections.profiles.ProfileService.getMyUserId(ProfileService.java:805)
	at com.ibm.sbt.services.client.connections.profiles.ProfileService.getMyProfile(ProfileService.java:824)
	at testing.Test01.main(Test01.java:34)

**Comment by prb112** [comment]
I believe this is now fixed. Segar if there is still an issue please ping/comment
