### ISSUE TITLE
Create a stand-alone wiki => "Field permissions was not found or had no value"

### ISSUE THREAD

**Issue by NiklasA** [OpenNTF/SocialSDK#1729]
Hi Paul,

I am trying to create a stand-alone wiki. I am using the following code:
```
    WikiService aWikiService = new WikiService( basicEndpoint );

    Wiki aWiki = new Wiki();
    aWiki.setContent( "Test Content ..." );
    aWiki.setTitle( "Test Title ..." );

    Variables.aWikiService.createWiki( aWiki );
```

All the time I get the following error code:
```
com.ibm.sbt.services.client.ClientServicesException: Field permissions was not found or had no value
	at com.ibm.sbt.services.client.connections.wikis.WikiService.createWiki(WikiService.java:602)
	at com.ibm.sbt.services.client.connections.wikis.WikiService.createWiki(WikiService.java:374)
	at com.ibm.sbt.services.client.connections.wikis.WikiService.createWiki(WikiService.java:361)
	at de.timetoact.cce.util.Testing.createONEStandAloneWiki(Testing.java:38)
	at de.timetoact.cce.InitServlet.doGet(InitServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
...
```

Do you have any suggestion, how I could fix this issue? Did I forgot something?

Thank you in advance.

Best regards
Niklas

**Comment by prb112** [comment]
WikiService svc = new WikiService(endpoint);
	       
	        	try {
	        		HashSet<String> permissions = new HashSet<String>();
	        		permissions.add("private");
	        		Wiki wiki = new Wiki();
	        		wiki.setPermissions(permissions);
	        		wiki.setTitle("Test"+ System.currentTimeMillis());
	        		wiki.setLabel("Test" + System.currentTimeMillis());
	        		svc.createWiki(wiki);
					
				} catch (ClientServicesException e) {
					e.printStackTrace();
				}

Use that as an example.  Thanks Paul
